### ISSUE TITLE
Broken dependency: glslify

### ISSUE THREAD

**Issue by mrakow** [voxel/voxel-shader#10]
Install fails:
```
$ npm install voxel-shader
npm ERR! Linux 3.16.0-38-generic
npm ERR! argv "node" "/usr/bin/npm" "install" "voxel-shader"
npm ERR! node v0.10.25
npm ERR! npm  v3.5.2
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/esprima-six
npm ERR! 404 
npm ERR! 404  'esprima-six' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'astw'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     /data/Documents/Projects/voxeltest/npm-debug.log
```
The issue lies in the glslify dependency: `$ npm install glslify` succeeds, but `$ npm install glslify@1.6` fails.

Proposed solution: Move on to glslify 2+

**Comment by z3t0** [comment]
Also having this problem...

**Comment by z3t0** [comment]
changing the version results in other problems...

**Comment by deathcap** [comment]
http://stackoverflow.com/questions/33608630/what-happened-to-the-esprima-six-npm-module says esprima-six was unpublished, recommends switching to esprima 2.x. Since it is only a transitive dependency, to test updating to glslify 2+ (and other dependencies if needed).
